/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include<iostream>
#include<cstdint>
using namespace std;

uint64_t find_even_fib_series(uint64_t num)
{
  uint64_t a = 0, b = 1;

  uint64_t sum = 0;
  uint64_t even_sum =0;
  while( sum < num)
  {
    sum = a + b;
    if( !(sum % 2))
    {
     cout<<sum << " ";
     even_sum += sum;
    }
    b = a;
    a = sum;
  }
  return even_sum;
}

int main(void)
{
   cout<<"The sum of even fib numbers is :: "<<find_even_fib_series(4*1000000)<<endl;
}
